// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpNVVloR8uWX5jO51weQeQx4DliMtv3s8',
    appId: '1:551520656953:web:a082d1106d5734cacb77e8',
    messagingSenderId: '551520656953',
    projectId: 'goziapp-f75ab',
    authDomain: 'goziapp-f75ab.firebaseapp.com',
    storageBucket: 'goziapp-f75ab.appspot.com',
    measurementId: 'G-FMTJXFYH8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgoiIHYQWO6yN2AnufrY5a2OfUixmey4s',
    appId: '1:551520656953:android:57396989c024dcc0cb77e8',
    messagingSenderId: '551520656953',
    projectId: 'goziapp-f75ab',
    storageBucket: 'goziapp-f75ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDrxVwIMV87RgRr5oeEef6WvtzFGZ0HvM',
    appId: '1:551520656953:ios:e451b1812fa20325cb77e8',
    messagingSenderId: '551520656953',
    projectId: 'goziapp-f75ab',
    storageBucket: 'goziapp-f75ab.appspot.com',
    iosClientId:
        '551520656953-eb3q49hfbbk22m1gpar8deame607m3vk.apps.googleusercontent.com',
    iosBundleId: 'com.example.grozziieapk',
  );
}
